[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
serde_json = "1.0.132"
yew = { version = "0.21.0", features = ["csr"] }
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
web-sys = "0.3.72"
